# Generated by Django 5.1.4 on 2025-03-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCOSPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('blood_group', models.CharField(max_length=3)),
                ('pulse_rate', models.IntegerField()),
                ('rr', models.IntegerField()),
                ('cycle_length', models.IntegerField()),
                ('marriage_status', models.IntegerField()),
                ('pregnant', models.BooleanField()),
                ('hip', models.FloatField()),
                ('waist', models.FloatField()),
                ('waist_hip_ratio', models.FloatField()),
                ('weight_gain', models.BooleanField()),
                ('hair_growth', models.BooleanField()),
                ('skin_darkening', models.BooleanField()),
                ('hair_loss', models.BooleanField()),
                ('pimples', models.BooleanField()),
                ('fast_food', models.BooleanField()),
                ('regular_exercise', models.BooleanField()),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcos_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
