# Generated by Django 5.1.4 on 2025-04-01 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcosprediction',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='bp_diastolic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='bp_systolic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='cycle_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='fast_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='hair_growth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='hair_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='hip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='marriage_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='pimples',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='prediction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='pulse_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='regular_exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='rr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='skin_darkening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcos_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='waist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='waist_hip_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pcosprediction',
            name='weight_gain',
            field=models.BooleanField(default=False),
        ),
    ]
