# Generated by Django 5.1.4 on 2024-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='userType',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
