# Generated by Django 5.1.4 on 2025-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_register_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
