# Generated by Django 5.1.4 on 2025-01-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
