# Generated by Django 5.1.4 on 2025-01-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_feedback_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submit',
        ),
    ]
