# Generated by Django 5.1.4 on 2025-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_remove_feedback_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Date_submitted',
            field=models.DateField(null=True),
        ),
    ]
